/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Clases.*;
import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.RED;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aless
 */
public class AUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    Validador inicio=new Validador();
    CUsuarios almacenador = new CUsuarios();
    Correos correos = new Correos();
    BotonBonito adorna = new BotonBonito();
    
    public AUsuarios() {
        initComponents();
        
        this.getContentPane().setBackground(new Color(180, 0, 0));
       
        setLocationRelativeTo(null);
        
        Clases.CConexion objC = new Clases.CConexion();
        Clases.CUsuarios objU = new Clases.CUsuarios();
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        objC.establece();
        objU.mostrarUsuarios(tableTotalUsuarios);
        objC.cerrarC();
        
        ImageIcon icono = new ImageIcon("imagenesL/ca1.png");
        jLabel54.setIcon(icono);
        jLabel46.setIcon(new ImageIcon("imagenesL/u1.png"));
        icono = new ImageIcon("imagenesL/Diapositiva2.PNG");
        jLabel17.setIcon(icono);
        jLabel47.setIcon(new ImageIcon("imagenesL/n1.png"));
        jLabel47.setIcon(new ImageIcon("imagenesL/n1.png"));
        jLabel48.setIcon(new ImageIcon("imagenesL/p1.png"));
        jLabel49.setIcon(new ImageIcon("imagenesL/m11.png"));
        jLabel51.setIcon(new ImageIcon("imagenesL/g1.png"));
        jLabel52.setIcon(new ImageIcon("imagenesL/r1.png"));
        jLabel53.setIcon(new ImageIcon("imagenesL/f1.png"));
        jLabel45.setIcon(new ImageIcon("imagenesL/ca2.png"));
        
        icono = new ImageIcon("imagenesL/ojo1.png");
        btnVer.setIcon(icono);
        btnVer2.setIcon(icono);
        icono = new ImageIcon("imagenesL/ojo2.png");
        btnVer1.setIcon(icono);
        btnVer3.setIcon(icono);
        
        adorna.personalizarBoton(btnGuardar);
        adorna.personalizarBoton(btnModificar);
        adorna.personalizarBoton(btnEliminar);
        adorna.personalizarBoton(btnVaciar2);
        adorna.personalizarBoton(btnAceptar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
8     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JDialog();
        JCalendario = new com.toedter.calendar.JDateChooser();
        txtNombre3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rMasculino = new javax.swing.JRadioButton();
        rFemenino = new javax.swing.JRadioButton();
        btnVaciar2 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        ErrorC2 = new javax.swing.JLabel();
        ErrorNombre = new javax.swing.JLabel();
        ErrorAP = new javax.swing.JLabel();
        ErrorAM = new javax.swing.JLabel();
        ErrorG = new javax.swing.JLabel();
        ErrorN = new javax.swing.JLabel();
        ErrorCorreo = new javax.swing.JLabel();
        ErrorC1 = new javax.swing.JLabel();
        txtContrasena2 = new javax.swing.JPasswordField();
        txtContrasena1 = new javax.swing.JPasswordField();
        btnVer = new javax.swing.JButton();
        btnVer1 = new javax.swing.JButton();
        btnVer2 = new javax.swing.JButton();
        btnVer3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rCaja = new javax.swing.JRadioButton();
        rAdmin = new javax.swing.JRadioButton();
        ErrorR = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        generoG = new javax.swing.ButtonGroup();
        rangoG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        txtRango = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTotalUsuarios = new javax.swing.JTable();

        Registro.setModal(true);
        Registro.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RegistroWindowClosing(evt);
            }
        });
        Registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Registro.getContentPane().add(JCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 320, 40));
        Registro.getContentPane().add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 320, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Registro");
        Registro.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));
        Registro.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Apellido Paterno:");
        Registro.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));
        Registro.getContentPane().add(txtAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 320, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Apellido Materno:");
        Registro.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));
        Registro.getContentPane().add(txtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 320, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Género:");
        Registro.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Fecha de Nacimiento:");
        Registro.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Correo:");
        Registro.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));
        Registro.getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 320, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Contraseña:");
        Registro.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Verificar Contraseña:");
        Registro.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        generoG.add(rMasculino);
        rMasculino.setText("Hombre");
        rMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMasculinoActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(rMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        generoG.add(rFemenino);
        rFemenino.setText("Mujer");
        Registro.getContentPane().add(rFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        btnVaciar2.setBackground(new java.awt.Color(255, 153, 153));
        btnVaciar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVaciar2.setText("Vaciar");
        btnVaciar2.setBorder(null);
        btnVaciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciar2ActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnVaciar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 150, 40));

        btnAceptar.setBackground(new java.awt.Color(255, 153, 153));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 570, 150, 40));
        Registro.getContentPane().add(ErrorC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 320, 30));
        Registro.getContentPane().add(ErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 320, 20));
        Registro.getContentPane().add(ErrorAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 320, 20));
        Registro.getContentPane().add(ErrorAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 320, 20));
        Registro.getContentPane().add(ErrorG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 230, 20));
        Registro.getContentPane().add(ErrorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 320, 20));
        Registro.getContentPane().add(ErrorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 320, 20));
        Registro.getContentPane().add(ErrorC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 320, 20));
        Registro.getContentPane().add(txtContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 320, 40));
        Registro.getContentPane().add(txtContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 320, 40));

        btnVer.setBorderPainted(false);
        btnVer.setContentAreaFilled(false);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, 40));

        btnVer1.setBorderPainted(false);
        btnVer1.setContentAreaFilled(false);
        btnVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1ActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, -1, 40));

        btnVer2.setBorderPainted(false);
        btnVer2.setContentAreaFilled(false);
        btnVer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer2ActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnVer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, -1, 40));

        btnVer3.setBorderPainted(false);
        btnVer3.setContentAreaFilled(false);
        btnVer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer3ActionPerformed(evt);
            }
        });
        Registro.getContentPane().add(btnVer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, -1, 40));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Nombre(s):");
        Registro.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Rango:");
        Registro.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        rangoG.add(rCaja);
        rCaja.setText("Caja");
        Registro.getContentPane().add(rCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        rangoG.add(rAdmin);
        rAdmin.setText("Administrador");
        Registro.getContentPane().add(rAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 100, -1));
        Registro.getContentPane().add(ErrorR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 320, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 40, 50));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 40, 50));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 50));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 40, 50));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 40, 60));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 40, 50));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 40, 50));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 40, 50));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Registro.getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 40, 50));
        Registro.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 720));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuarios"));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel5.setText("Género:");

        txtID.setEnabled(false);

        btnGuardar.setText("Añadir");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Correo:");

        jLabel7.setText("F. Nacimiento:");

        txtFN.setEnabled(false);

        jLabel8.setText("Contraseña:");

        jLabel9.setText("Rango:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(txtID)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellidoM, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtApellidoP, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                                .addGap(22, 22, 22)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56)
                                .addComponent(txtCO))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(txtContrasena))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(58, 58, 58)
                                .addComponent(txtRango)))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Usuarios"));

        tableTotalUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableTotalUsuarios.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tableTotalUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTotalUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTotalUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Clases.CUsuarios objU = new Clases.CUsuarios();
        Registro.setSize(1280, 720);
        Registro.setLocationRelativeTo(null);
        Registro.setVisible(true); 
        objU.mostrarUsuarios(tableTotalUsuarios);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tableTotalUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTotalUsuariosMouseClicked
        Clases.CUsuarios objU = new Clases.CUsuarios();
        objU.Seleccionar(tableTotalUsuarios, txtID, txtNombre, txtApellidoP, txtApellidoM, txtGenero, txtFN, txtCO, txtContrasena, txtRango);
    }//GEN-LAST:event_tableTotalUsuariosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Clases.CUsuarios objU = new Clases.CUsuarios();
        String cn = correos.encriptar(txtContrasena.getText());
        txtContrasena.setText(cn);
        objU.modificarUsuario(txtID, txtNombre, txtApellidoP, txtApellidoM, txtGenero, txtCO, txtContrasena, txtRango);
        objU.mostrarUsuarios(tableTotalUsuarios);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Clases.CUsuarios objU = new Clases.CUsuarios();
        objU.eliminarUsuario(txtID);
        objU.mostrarUsuarios(tableTotalUsuarios);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVaciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciar2ActionPerformed
        txtNombre3.setText("");
        txtAP.setText("");
        txtAM.setText("");
        generoG.clearSelection();
        rangoG.clearSelection();
        JCalendario.setDate(null);
        txtCorreo.setText("");
        txtContrasena1.setText("");
        txtContrasena2.setText("");

        ErrorNombre.setText("");
        ErrorAP.setText("");
        ErrorAM.setText("");
        ErrorG.setText("");
        ErrorN.setText("");
        ErrorCorreo.setText("");
        ErrorC1.setText("");
        ErrorC2.setText("");
        ErrorR.setText("");
    }//GEN-LAST:event_btnVaciar2ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String n=txtNombre3.getText();
        boolean rn=false;
        if (inicio.ValidarTexto(n)==true){
            rn=true;
            ErrorNombre.setText("");
            ErrorNombre.setForeground(BLACK);
        }
        else {
            ErrorNombre.setText("El nombre debe incluir solo letras");
            ErrorNombre.setForeground(RED);
        }
        boolean rap=false;
        String ap=txtAP.getText();
        if (inicio.ValidarTexto(ap)==true){
            rap=true;
            ErrorAP.setText("");
            ErrorAP.setForeground(BLACK);
        }
        else {
            ErrorAP.setText("El Apellido debe incluir solo letras");
            ErrorAP.setForeground(RED);
        }
        boolean ram=false;
        String am=txtAM.getText();
        if (inicio.ValidarTexto(am)==true){
            ram=true;
            ErrorAM.setText("");
            ErrorAM.setForeground(BLACK);
        }
        else {
            ErrorAM.setText("El Apellido debe incluir solo letras");
            ErrorAM.setForeground(RED);
        }

        boolean rg=false;
        String g="";

        if (generoG.getSelection()==null){
            ErrorG.setText("Debe elegir un género");
            ErrorG.setForeground(RED);
        }
        else {
            rg=true;
            ErrorG.setText("");
            ErrorG.setForeground(BLACK);
            if(rMasculino.isSelected()){
                g="Hombre";
            }
            if(rFemenino.isSelected()){
                g="Mujer";
            }
        }

        boolean rang=false;
        char r='c';

        if (rangoG.getSelection()==null){
            ErrorR.setText("Debe elegir un rango");
            ErrorR.setForeground(RED);
        }
        else {
            rang=true;
            ErrorR.setText("");
            ErrorR.setForeground(BLACK);
            if(rCaja.isSelected()){
                r='c';
            }
            if(rAdmin.isSelected()){
                r='e';
            }
        }

        boolean rc=false;
        if (JCalendario.getDate()==null){
            ErrorN.setText("Debe elegir una fecha");
            ErrorN.setForeground(RED);
        }
        else {
            rc=true;
            ErrorN.setText("");
            ErrorN.setForeground(BLACK);
        }

        boolean ru=false;
        if (inicio.validarCorreo(txtCorreo.getText().toLowerCase())==true){
            if(almacenador.correoEx(txtCorreo.getText())){
                ErrorCorreo.setText("El correo ya pertenece a una cuenta");
                ErrorCorreo.setForeground(RED);
            } else{
                ru=true;
                ErrorCorreo.setText("");
                ErrorCorreo.setForeground(BLACK);
            }
        }
        else{
            ErrorCorreo.setText("El correo ingresado no tiene la estructura correcta");
            ErrorCorreo.setForeground(RED);
        }

        boolean rc1=false;
        if(inicio.validarContrasena(txtContrasena1.getText())==true){
            rc1=true;
            ErrorC1.setText("");
            ErrorC1.setForeground(BLACK);
        }
        else{
            ErrorC1.setText("La contraseña no tiene 8 caracteres");
            ErrorC1.setForeground(RED);
        }

        boolean rc2=false;
        if (!txtContrasena2.getText().equals(txtContrasena1.getText())||txtContrasena2.getText()==null){
            ErrorC2.setText("La contraseña no es la misma que la ingresada");
            ErrorC2.setForeground(RED);
        }
        else {
            rc2=true;
            ErrorC2.setText("");
            ErrorC2.setForeground(BLACK);
        }

        if(rn==true&&rap==true&&ram==true&&rg==true&&rang==true&&rc==true&&ru==true&&rc1==true&&rc2==true){
            String pass = Correos.encriptar(txtContrasena2.getText());
            almacenador.agregarUsuario(n, ap, am, g, JCalendario.getDate(), txtCorreo.getText(),pass,r);
            if(Correos.enviarCorreoConPDF(txtCorreo.getText(), Correos.generarPDF(n, ap, am, txtCorreo.getText(), txtContrasena1.getText()))){
                JOptionPane.showMessageDialog(null, "Correo enviado");
            }
            Registro.setVisible(false);
            btnVaciar2.doClick();
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        txtContrasena1.setEchoChar((char)0);
        btnVer.setVisible(false);
        btnVer1.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1ActionPerformed
        txtContrasena1.setEchoChar('●');
        btnVer.setVisible(true);
        btnVer1.setVisible(false);
    }//GEN-LAST:event_btnVer1ActionPerformed

    private void btnVer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer2ActionPerformed
        txtContrasena2.setEchoChar((char)0);
        btnVer2.setVisible(false);
        btnVer3.setVisible(true);
    }//GEN-LAST:event_btnVer2ActionPerformed

    private void btnVer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer3ActionPerformed
        txtContrasena2.setEchoChar('●');
        btnVer2.setVisible(true);
        btnVer3.setVisible(false);
    }//GEN-LAST:event_btnVer3ActionPerformed

    private void rMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rMasculinoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String Botones[]={"Cerrar","Cancelar"};
        int eleccion=JOptionPane.showOptionDialog(this,"¿Seguro que desea salir?","Titulo",0,0,null,Botones,this);
        if (eleccion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void RegistroWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistroWindowClosing
        int opcion = JOptionPane.showConfirmDialog(
                Registro,
                "¿Deseas cerrar el Registro?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION
            );

        if (opcion == JOptionPane.YES_OPTION) {
            btnVaciar2.doClick();
            System.exit(0);   
        }
    }//GEN-LAST:event_RegistroWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorAM;
    private javax.swing.JLabel ErrorAP;
    private javax.swing.JLabel ErrorC1;
    private javax.swing.JLabel ErrorC2;
    private javax.swing.JLabel ErrorCorreo;
    private javax.swing.JLabel ErrorG;
    private javax.swing.JLabel ErrorN;
    private javax.swing.JLabel ErrorNombre;
    private javax.swing.JLabel ErrorR;
    private com.toedter.calendar.JDateChooser JCalendario;
    private javax.swing.JDialog Registro;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVaciar2;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVer1;
    private javax.swing.JButton btnVer2;
    private javax.swing.JButton btnVer3;
    private javax.swing.ButtonGroup generoG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rAdmin;
    private javax.swing.JRadioButton rCaja;
    private javax.swing.JRadioButton rFemenino;
    private javax.swing.JRadioButton rMasculino;
    private javax.swing.ButtonGroup rangoG;
    private javax.swing.JTable tableTotalUsuarios;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCO;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JPasswordField txtContrasena1;
    private javax.swing.JPasswordField txtContrasena2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFN;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre3;
    private javax.swing.JTextField txtRango;
    // End of variables declaration//GEN-END:variables
}
