/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Clases.CUsuarios;
import Clases.Correos;
import javax.swing.*;
import static java.awt.Color.BLACK;
import static java.awt.Color.RED;

/**
 *
 * @author aless
 */
public class LoginEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    CUsuarios almacenador = new CUsuarios();
    
    public LoginEmpresa() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        JScrollPane scrollPane = new JScrollPane(panelPrincipal);
        this.setContentPane(scrollPane); // Reemplaza el contenido del JFrame con el JScrollPane
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        btnVer5.setVisible(false);
        
        ImageIcon icono = new ImageIcon("imagenesL/Diapositiva1.PNG");
        jLabel36.setIcon(icono);
        icono = new ImageIcon("imagenesL/rojo1.png");
        jLabel35.setIcon(icono);
        jLabel37.setIcon(icono);
        jLabel38.setIcon(icono);
        icono = new ImageIcon("imagenesL/ca1.png");
        jLabel40.setIcon(icono);
        icono = new ImageIcon("imagenesL/u1.png");
        jLabel43.setIcon(icono);
        
        icono = new ImageIcon("imagenesL/ojo1.png");
        btnVer4.setIcon(icono);
        icono = new ImageIcon("imagenesL/ojo2.png");
        btnVer5.setIcon(icono);
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opt = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        VaciarIn = new javax.swing.JButton();
        IngresarIn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        lblError3 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        btnVer4 = new javax.swing.JButton();
        btnVer5 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtCO = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿A qué desea ingresar?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptLayout = new javax.swing.GroupLayout(Opt.getContentPane());
        Opt.getContentPane().setLayout(OptLayout);
        OptLayout.setHorizontalGroup(
            OptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        OptLayout.setVerticalGroup(
            OptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VaciarIn.setBackground(new java.awt.Color(255, 153, 153));
        VaciarIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VaciarIn.setText("Vaciar");
        VaciarIn.setBorder(null);
        VaciarIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaciarInActionPerformed(evt);
            }
        });
        panelPrincipal.add(VaciarIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 150, 40));

        IngresarIn.setBackground(new java.awt.Color(255, 153, 153));
        IngresarIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngresarIn.setText("Ingresar");
        IngresarIn.setBorder(null);
        IngresarIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarInActionPerformed(evt);
            }
        });
        panelPrincipal.add(IngresarIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, 150, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Contraseña:");
        panelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));
        panelPrincipal.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 380, 40));
        panelPrincipal.add(lblError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 380, 30));
        panelPrincipal.add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 380, 20));

        btnVer4.setBorderPainted(false);
        btnVer4.setContentAreaFilled(false);
        btnVer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer4ActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnVer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 440, -1, 40));

        btnVer5.setBorderPainted(false);
        btnVer5.setContentAreaFilled(false);
        btnVer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer5ActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnVer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 440, -1, 40));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelPrincipal.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, -1, 200));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelPrincipal.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 40, 50));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelPrincipal.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 430, -1, 290));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelPrincipal.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 140, -1, -1));
        panelPrincipal.add(txtCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 380, 40));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setText("Correo:");
        panelPrincipal.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelPrincipal.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 40, 50));

        jLabel36.setBackground(new java.awt.Color(255, 255, 0));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelPrincipal.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 740));

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String Botones[]={"Cerrar","Cancelar"};
        int eleccion=JOptionPane.showOptionDialog(this,"¿Seguro que desea salir?","Titulo",0,0,null,Botones,this);
        if (eleccion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnVer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer5ActionPerformed
        // TODO add your handling code here:
        txtContrasena.setEchoChar('●');
        btnVer4.setVisible(true);
        btnVer5.setVisible(false);
    }//GEN-LAST:event_btnVer5ActionPerformed

    private void btnVer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer4ActionPerformed
        // TODO add your handling code here:
        txtContrasena.setEchoChar((char)0);
        btnVer4.setVisible(false);
        btnVer5.setVisible(true);
    }//GEN-LAST:event_btnVer4ActionPerformed

    private void VaciarInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaciarInActionPerformed
        txtCO.setText("");
        txtContrasena.setText("");
        lblError1.setText("");
        lblError3.setText("");
    }//GEN-LAST:event_VaciarInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AProductos empleado = new AProductos();
        empleado.setVisible(true); 
        this.setVisible(false);
        panelPrincipal.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AUsuarios empleado = new AUsuarios();
        empleado.setVisible(true);
        this.setVisible(false);
        panelPrincipal.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IngresarInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarInActionPerformed
        // TODO add your handling code here:
        String correo = txtCO.getText();
        String contrasena = txtContrasena.getText();
        boolean c = false;
        boolean co = false;

        if (correo.equals("")){
            lblError1.setText("Ingrese un Correo");
            lblError1.setForeground(RED);
        }
        else{
            lblError1.setText("");
            lblError1.setForeground(BLACK);
            c = true;
        }

        if (contrasena.equals("")){
            lblError3.setText("Ingrese una Contraseña");
            lblError3.setForeground(RED);
        }
        else{
            lblError3.setText("");
            lblError3.setForeground(BLACK);
            co = true;
        }

        if (c==true && co==true){
            String pass = Correos.encriptar(contrasena);
            char rango = almacenador.encontrarUsuario(correo, pass);
            if (rango == 'c'){
                ACaja cliente = new ACaja();
                cliente.setVisible(true);
                lblError3.setText("");
                lblError3.setForeground(BLACK);
                this.setVisible(false);

            }
            if (rango == 'e'){
                Opt.setVisible(true);
                Opt.pack();
                Opt.setLocationRelativeTo(null);
                lblError3.setText("");
                lblError3.setForeground(BLACK);
            }
            if (rango == 'n'){
                lblError3.setText("El Correo no se encontró o la contraseña es incorrecta");
                lblError3.setForeground(RED);
            }
        }
    }//GEN-LAST:event_IngresarInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginEmpresa frame = new LoginEmpresa();
                frame.setVisible(true);
            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarIn;
    private javax.swing.JDialog Opt;
    private javax.swing.JButton VaciarIn;
    private javax.swing.JButton btnVer4;
    private javax.swing.JButton btnVer5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtCO;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}